-- MySQL Script generated by MySQL Workbench
-- Sat Aug  1 22:46:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deporta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deporta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deporta` DEFAULT CHARACTER SET utf8;
USE `deporta`;
-- -----------------------------------------------------
-- Table `deporta`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`ROL` (
  `idROL` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idROL`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deporta`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL UNIQUE,
  `telefono` VARCHAR(20) NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUSUARIO`),
  INDEX `fk_USUARIO_ROL_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_ROL`
    FOREIGN KEY (`id_rol`)
    REFERENCES `deporta`.`ROL` (`idROL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deporta`.`DISTRITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`DISTRITO` (
  `idDISTRITO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDISTRITO`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `deporta`.`COMPLEJO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`COMPLEJO` (
  `idCOMPLEJO` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_distrito` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(100) NOT NULL UNIQUE,
  `ruc` VARCHAR(11) NOT NULL UNIQUE,

  PRIMARY KEY (`idCOMPLEJO`),

  INDEX `fk_COMPLEJO_USUARIO_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_COMPLEJO_DISTRITO_idx` (`id_distrito` ASC) VISIBLE,

  CONSTRAINT `fk_COMPLEJO_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `deporta`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_COMPLEJO_DISTRITO`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `deporta`.`DISTRITO` (`idDISTRITO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `deporta`.`DEPORTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`DEPORTE` (
  `idDEPORTE` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,

  PRIMARY KEY (`idDEPORTE`)
)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `deporta`.`ESPACIO_DEPORTIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`ESPACIO_DEPORTIVO` (
  `idESPACIO_DEPORTIVO` INT NOT NULL AUTO_INCREMENT,
  `id_complejo` INT NOT NULL,
  `id_deporte` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `url_imagen` VARCHAR(255) NOT NULL,

  PRIMARY KEY (`idESPACIO_DEPORTIVO`),

  INDEX `fk_ESPACIO_COMPLEJO_idx` (`id_complejo` ASC) VISIBLE,
  INDEX `fk_ESPACIO_DEPORTE_idx` (`id_deporte` ASC) VISIBLE,

  CONSTRAINT `fk_ESPACIO_COMPLEJO`
    FOREIGN KEY (`id_complejo`)
    REFERENCES `deporta`.`COMPLEJO` (`idCOMPLEJO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_ESPACIO_DEPORTE`
    FOREIGN KEY (`id_deporte`)
    REFERENCES `deporta`.`DEPORTE` (`idDEPORTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deporta`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`RESERVA` (
  `idRESERVA` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_espacio_deportivo` INT NOT NULL,
  `fecha_hora_inicio` DATETIME NOT NULL,
  `fecha_hora_fin` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,

  PRIMARY KEY (`idRESERVA`),

  INDEX `fk_RESERVA_USUARIO_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_RESERVA_ESPACIO_idx` (`id_espacio_deportivo` ASC) VISIBLE,

  CONSTRAINT `fk_RESERVA_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `deporta`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_RESERVA_ESPACIO`
    FOREIGN KEY (`id_espacio_deportivo`)
    REFERENCES `deporta`.`ESPACIO_DEPORTIVO` (`idESPACIO_DEPORTIVO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `deporta`.`METODO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`METODO_PAGO` (
  `idMETODO_PAGO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,

  PRIMARY KEY (`idMETODO_PAGO`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `deporta`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deporta`.`PAGO` (
  `idPAGO` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `id_metodo_pago` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,

  PRIMARY KEY (`idPAGO`),

  INDEX `fk_PAGO_RESERVA_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_PAGO_METODO_idx` (`id_metodo_pago` ASC) VISIBLE,

  CONSTRAINT `fk_PAGO_RESERVA`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `deporta`.`RESERVA` (`idRESERVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_PAGO_METODO`
    FOREIGN KEY (`id_metodo_pago`)
    REFERENCES `deporta`.`METODO_PAGO` (`idMETODO_PAGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- DATOS INICIALES
-- -----------------------------------------------------

INSERT INTO ROL (nombre)
VALUES
('ADMIN'),
('USUARIO');

INSERT INTO DEPORTE (nombre)
VALUES
('Fútbol'),
('Vóley'),
('Básquet'),
('Tenis'),
('Natación');

INSERT INTO METODO_PAGO (nombre)
VALUES
('Visa'),
('Mastercard'),
('Yape'),
('Efectivo');

SELECT * FROM ROL;
SELECT * FROM DEPORTE;
SELECT * FROM METODO_PAGO;
SELECT * FROM usuario;
SELECT * FROM complejo;
SELECT * FROM deporte;




ALTER TABLE DEPORTE
ADD UNIQUE(nombre);

ALTER TABLE ROL
ADD UNIQUE(nombre);

ALTER TABLE METODO_PAGO
ADD UNIQUE(nombre);

SELECT
    c.idCOMPLEJO,
    c.nombre,
    c.id_distrito,
    d.nombre AS distrito
FROM COMPLEJO c
INNER JOIN DISTRITO d
ON c.id_distrito = d.idDISTRITO;

